#!/usr/bin/env python3
"""
convert.py — Convert SuperOPC skills/agents/commands into tool-specific formats.

Reads all markdown source files from skills/, agents/, commands/ and outputs
converted files to integrations/<tool>/.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "integrations"
TODAY = date.today().isoformat()
PLUGIN_VERSION = json.loads((REPO_ROOT / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8")).get(
    "version",
    "0.1.0",
)

SKILL_DIRS = [
    "skills/product",
    "skills/engineering",
    "skills/business",
    "skills/intelligence",
    "skills/learning",
    "skills/using-superopc",
]
AGENT_DIR = "agents"
COMMAND_DIR = "commands/opc"
VALID_TOOLS = ("cursor", "windsurf", "gemini-cli", "opencode", "openclaw", "all")


@dataclass
class ParsedMarkdown:
    meta: dict[str, str]
    body: str


def slugify(name: str) -> str:
    return re.sub(r"(^-|-$)", "", re.sub(r"[^a-z0-9]+", "-", name.lower()))


def parse_frontmatter(content: str) -> ParsedMarkdown:
    match = re.match(r"^---\n([\s\S]*?)\n---\n([\s\S]*)$", content)
    if not match:
        return ParsedMarkdown(meta={}, body=content)

    meta: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        parsed = value.strip().strip('"').strip("'")
        meta[key.strip()] = parsed

    return ParsedMarkdown(meta=meta, body=match.group(2))


def collect_files(directories: list[str], suffix: str = ".md") -> list[Path]:
    results: list[Path] = []
    for directory in directories:
        abs_dir = REPO_ROOT / directory
        if abs_dir.exists():
            results.extend(sorted(path for path in abs_dir.rglob(f"*{suffix}") if path.is_file()))
    return sorted(results)


def ensure_dir(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)


def write_file(file_path: Path, content: str) -> None:
    ensure_dir(file_path.parent)
    file_path.write_text(content, encoding="utf-8")


def convert_cursor(files: list[Path], out_dir: Path) -> int:
    count = 0
    rules_dir = out_dir / "cursor" / "rules"
    for file in files:
        parsed = parse_frontmatter(file.read_text(encoding="utf-8"))
        name = parsed.meta.get("name")
        if not name:
            continue
        description = parsed.meta.get("description", "")
        content = f"---\ndescription: {description}\nglobs: \"\"\nalwaysApply: false\n---\n{parsed.body}"
        write_file(rules_dir / f"{slugify(name)}.mdc", content)
        count += 1
    return count


def convert_windsurf(files: list[Path], out_dir: Path) -> int:
    count = 0
    parts = [
        "# SuperOPC - AI Rules for Windsurf\n",
        "#\n",
        "# One-Person Company AI Operating System\n",
        f"# Generated by scripts/convert.py on {TODAY}\n",
        "#\n\n",
    ]
    for file in files:
        parsed = parse_frontmatter(file.read_text(encoding="utf-8"))
        name = parsed.meta.get("name")
        if not name:
            continue
        description = parsed.meta.get("description", "")
        parts.extend(
            [
                f"{'=' * 80}\n",
                f"## {name}\n",
                f"{description}\n",
                f"{'=' * 80}\n\n",
                parsed.body,
                "\n\n",
            ]
        )
        count += 1

    write_file(out_dir / "windsurf" / ".windsurfrules", "".join(parts))
    return count


def convert_gemini_cli(files: list[Path], out_dir: Path) -> int:
    count = 0
    skills_base = out_dir / "gemini-cli" / "skills"
    for file in files:
        parsed = parse_frontmatter(file.read_text(encoding="utf-8"))
        name = parsed.meta.get("name")
        if not name:
            continue
        description = parsed.meta.get("description", "")
        content = f"---\nname: {slugify(name)}\ndescription: {description}\n---\n{parsed.body}"
        write_file(skills_base / slugify(name) / "SKILL.md", content)
        count += 1

    write_file(
        out_dir / "gemini-cli" / "gemini-extension.json",
        json.dumps({"name": "superopc", "version": PLUGIN_VERSION}, ensure_ascii=False, indent=2),
    )
    return count


def convert_opencode(files: list[Path], out_dir: Path) -> int:
    count = 0
    agents_dir = out_dir / "opencode" / "agents"
    for file in files:
        parsed = parse_frontmatter(file.read_text(encoding="utf-8"))
        name = parsed.meta.get("name")
        if not name:
            continue
        description = parsed.meta.get("description", "")
        content = f"---\nname: {name}\ndescription: {description}\nmode: subagent\n---\n{parsed.body}"
        write_file(agents_dir / f"{slugify(name)}.md", content)
        count += 1
    return count


def split_openclaw_body(body: str, name: str, description: str) -> tuple[str, str]:
    soul_sections: list[str] = []
    agent_sections: list[str] = []
    current_target = "agents"
    current_lines: list[str] = []

    def flush(target: str, lines: list[str]) -> None:
        section = "\n".join(lines)
        if not section:
            return
        if target == "soul":
            soul_sections.append(section)
        else:
            agent_sections.append(section)

    for line in body.splitlines():
        if line.startswith("## "):
            flush(current_target, current_lines)
            current_lines = []
            lowered = line.lower()
            if any(token in lowered for token in ("identity", "communication", "style", "critical.rule", "rules.you.must")):
                current_target = "soul"
            else:
                current_target = "agents"
        current_lines.append(line)

    flush(current_target, current_lines)
    soul = "\n".join(soul_sections).strip() or f"# {name}\n{description}\n"
    agents = "\n".join(agent_sections).strip() or body
    return soul, agents


def convert_openclaw(files: list[Path], out_dir: Path) -> int:
    count = 0
    for file in files:
        parsed = parse_frontmatter(file.read_text(encoding="utf-8"))
        name = parsed.meta.get("name")
        if not name:
            continue
        description = parsed.meta.get("description", "")
        agent_dir = out_dir / "openclaw" / slugify(name)
        soul, agents = split_openclaw_body(parsed.body, name, description)
        write_file(agent_dir / "SOUL.md", soul)
        write_file(agent_dir / "AGENTS.md", agents)
        write_file(agent_dir / "IDENTITY.md", f"# {name}\n{description}\n")
        count += 1
    return count


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert SuperOPC formats for other tools.")
    parser.add_argument("--tool", choices=VALID_TOOLS, default="all")
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    out_dir = Path(args.out).resolve()

    print("\nSuperOPC Format Converter")
    print(f"  Repo:   {REPO_ROOT}")
    print(f"  Output: {out_dir}")
    print(f"  Tool:   {args.tool}")
    print(f"  Date:   {TODAY}\n")

    skill_files = collect_files(SKILL_DIRS)
    agent_files = collect_files([AGENT_DIR])
    command_files = collect_files([COMMAND_DIR])
    all_files = [*skill_files, *agent_files, *command_files]

    print(f"  Found: {len(skill_files)} skills, {len(agent_files)} agents, {len(command_files)} commands\n")

    tools_to_run = list(VALID_TOOLS[:-1]) if args.tool == "all" else [args.tool]
    total = 0
    for tool in tools_to_run:
        if tool == "cursor":
            count = convert_cursor(all_files, out_dir)
        elif tool == "windsurf":
            count = convert_windsurf(all_files, out_dir)
        elif tool == "gemini-cli":
            count = convert_gemini_cli(all_files, out_dir)
        elif tool == "opencode":
            count = convert_opencode(all_files, out_dir)
        else:
            count = convert_openclaw(all_files, out_dir)

        print(f"  [OK] {tool}: {count} items converted")
        total += count

    print(f"\n  Done. Total: {total} conversions across {len(tools_to_run)} tool(s).\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
