#!/usr/bin/env node
/**
 * convert.js — Convert SuperOPC skills/agents/commands into tool-specific formats
 *
 * Reads all .md files from skills/, agents/, commands/ and outputs
 * converted files to integrations/<tool>/.
 *
 * Supported tools:
 *   cursor     - .cursor/rules/*.mdc files
 *   windsurf   - Single .windsurfrules file
 *   gemini-cli - Gemini CLI skill format
 *   opencode   - .opencode/agents/*.md format
 *   openclaw   - OpenClaw SOUL.md + AGENTS.md format
 *   all        - All tools (default)
 *
 * Usage:
 *   node scripts/convert.js [--tool <name>] [--out <dir>]
 *
 * Source pattern: agency-agents/scripts/convert.sh
 * Adapted for SuperOPC (Node.js, cross-platform, skills+agents+commands)
 */

const fs = require('fs');
const path = require('path');

// --- Config ---
const REPO_ROOT = path.resolve(__dirname, '..');
const DEFAULT_OUT = path.join(REPO_ROOT, 'integrations');
const TODAY = new Date().toISOString().split('T')[0];

const SKILL_DIRS = ['skills/product', 'skills/engineering', 'skills/business', 'skills/intelligence', 'skills/learning', 'skills/using-superopc'];
const AGENT_DIR = 'agents';
const COMMAND_DIR = 'commands/opc';

// --- Helpers ---

function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: content };

  const meta = {};
  match[1].split('\n').forEach(line => {
    const colonIdx = line.indexOf(':');
    if (colonIdx > 0) {
      const key = line.slice(0, colonIdx).trim();
      let value = line.slice(colonIdx + 1).trim();
      if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
      if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
      meta[key] = value;
    }
  });

  return { meta, body: match[2] };
}

function collectFiles(dirs, ext = '.md') {
  const files = [];
  for (const dir of dirs) {
    const absDir = path.join(REPO_ROOT, dir);
    if (!fs.existsSync(absDir)) continue;
    walkDir(absDir, ext, files);
  }
  return files.sort();
}

function walkDir(dir, ext, result) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkDir(fullPath, ext, result);
    } else if (entry.name.endsWith(ext)) {
      result.push(fullPath);
    }
  }
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
}

// --- Converters ---

function convertCursor(files, outDir) {
  let count = 0;
  const rulesDir = path.join(outDir, 'cursor', 'rules');

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const { meta, body } = parseFrontmatter(content);
    if (!meta.name) continue;

    const slug = slugify(meta.name);
    const description = meta.description || '';

    // Cursor .mdc format
    const mdc = `---
description: ${description}
globs: ""
alwaysApply: false
---
${body}`;

    writeFile(path.join(rulesDir, `${slug}.mdc`), mdc);
    count++;
  }
  return count;
}

function convertWindsurf(files, outDir) {
  let count = 0;
  const parts = [
    '# SuperOPC — AI Rules for Windsurf\n',
    '#\n',
    '# One-Person Company AI Operating System\n',
    `# Generated by scripts/convert.js on ${TODAY}\n`,
    '#\n\n',
  ];

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const { meta, body } = parseFrontmatter(content);
    if (!meta.name) continue;

    const description = meta.description || '';
    parts.push(`${'='.repeat(80)}\n`);
    parts.push(`## ${meta.name}\n`);
    parts.push(`${description}\n`);
    parts.push(`${'='.repeat(80)}\n\n`);
    parts.push(body);
    parts.push('\n\n');
    count++;
  }

  writeFile(path.join(outDir, 'windsurf', '.windsurfrules'), parts.join(''));
  return count;
}

function convertGeminiCli(files, outDir) {
  let count = 0;
  const skillsBase = path.join(outDir, 'gemini-cli', 'skills');

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const { meta, body } = parseFrontmatter(content);
    if (!meta.name) continue;

    const slug = slugify(meta.name);
    const description = meta.description || '';

    const skillMd = `---
name: ${slug}
description: ${description}
---
${body}`;

    writeFile(path.join(skillsBase, slug, 'SKILL.md'), skillMd);
    count++;
  }

  // Extension manifest
  writeFile(path.join(outDir, 'gemini-cli', 'gemini-extension.json'), JSON.stringify({
    name: 'superopc',
    version: '0.1.0'
  }, null, 2));

  return count;
}

function convertOpencode(files, outDir) {
  let count = 0;
  const agentsDir = path.join(outDir, 'opencode', 'agents');

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const { meta, body } = parseFrontmatter(content);
    if (!meta.name) continue;

    const slug = slugify(meta.name);
    const description = meta.description || '';

    const agentMd = `---
name: ${meta.name}
description: ${description}
mode: subagent
---
${body}`;

    writeFile(path.join(agentsDir, `${slug}.md`), agentMd);
    count++;
  }
  return count;
}

function convertOpenclaw(files, outDir) {
  let count = 0;

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const { meta, body } = parseFrontmatter(content);
    if (!meta.name) continue;

    const slug = slugify(meta.name);
    const description = meta.description || '';
    const agentDir = path.join(outDir, 'openclaw', slug);

    // Split body into SOUL (persona) and AGENTS (operations) by ## headers
    let soulContent = '';
    let agentsContent = '';
    let currentTarget = 'agents';
    let currentSection = '';

    for (const line of body.split('\n')) {
      if (/^##\s/.test(line)) {
        // Flush previous section
        if (currentTarget === 'soul') {
          soulContent += currentSection;
        } else {
          agentsContent += currentSection;
        }
        currentSection = '';

        // Classify header
        const lower = line.toLowerCase();
        if (/identity|communication|style|critical.rule|rules.you.must/.test(lower)) {
          currentTarget = 'soul';
        } else {
          currentTarget = 'agents';
        }
      }
      currentSection += line + '\n';
    }

    // Flush final section
    if (currentTarget === 'soul') {
      soulContent += currentSection;
    } else {
      agentsContent += currentSection;
    }

    writeFile(path.join(agentDir, 'SOUL.md'), soulContent || `# ${meta.name}\n${description}\n`);
    writeFile(path.join(agentDir, 'AGENTS.md'), agentsContent || body);
    writeFile(path.join(agentDir, 'IDENTITY.md'), `# ${meta.name}\n${description}\n`);

    count++;
  }
  return count;
}

// --- Main ---

function main() {
  const args = process.argv.slice(2);
  let tool = 'all';
  let outDir = DEFAULT_OUT;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--tool' && args[i + 1]) { tool = args[++i]; }
    if (args[i] === '--out' && args[i + 1]) { outDir = path.resolve(args[++i]); }
    if (args[i] === '--help' || args[i] === '-h') {
      console.log('Usage: node scripts/convert.js [--tool <name>] [--out <dir>]');
      console.log('Tools: cursor, windsurf, gemini-cli, opencode, openclaw, all');
      process.exit(0);
    }
  }

  const validTools = ['cursor', 'windsurf', 'gemini-cli', 'opencode', 'openclaw', 'all'];
  if (!validTools.includes(tool)) {
    console.error(`Unknown tool '${tool}'. Valid: ${validTools.join(', ')}`);
    process.exit(1);
  }

  console.log(`\nSuperOPC Format Converter`);
  console.log(`  Repo:   ${REPO_ROOT}`);
  console.log(`  Output: ${outDir}`);
  console.log(`  Tool:   ${tool}`);
  console.log(`  Date:   ${TODAY}\n`);

  // Collect all source files
  const skillFiles = collectFiles(SKILL_DIRS);
  const agentFiles = collectFiles([AGENT_DIR]);
  const commandFiles = collectFiles([COMMAND_DIR]);
  const allFiles = [...skillFiles, ...agentFiles, ...commandFiles];

  console.log(`  Found: ${skillFiles.length} skills, ${agentFiles.length} agents, ${commandFiles.length} commands\n`);

  const toolsToRun = tool === 'all' ? ['cursor', 'windsurf', 'gemini-cli', 'opencode', 'openclaw'] : [tool];

  let total = 0;
  for (const t of toolsToRun) {
    let count = 0;
    switch (t) {
      case 'cursor':     count = convertCursor(allFiles, outDir); break;
      case 'windsurf':   count = convertWindsurf(allFiles, outDir); break;
      case 'gemini-cli': count = convertGeminiCli(allFiles, outDir); break;
      case 'opencode':   count = convertOpencode(allFiles, outDir); break;
      case 'openclaw':   count = convertOpenclaw(allFiles, outDir); break;
    }
    console.log(`  [OK] ${t}: ${count} items converted`);
    total += count;
  }

  console.log(`\n  Done. Total: ${total} conversions across ${toolsToRun.length} tool(s).\n`);
}

main();
